### ISSUE TITLE
create a benchmark based on DrugMechDB

### ISSUE THREAD

**Issue by andrewsu** [TranslatorSRI/Benchmarks#1]
DrugMechDB is a database of drug mechanisms expressed as paths through (or subgraphs of) a knowledge graph.  More info: https://github.com/SuLab/DrugMechDB

@cbizon and I will take the lead (at least initially) on trying to use this resource to create a benchmark.  (It might possibly build on https://github.com/Carolina1396/drug_mechanisms_rare_diseases_BioThingsExplorer, but maybe not...)

**Comment by andrewsu** [comment]
Next step, I will extend this notebook https://github.com/SuLab/DMDB_Analysis/blob/main/1_code/1_basic_dmdb_analysis.ipynb to output a CSV modeled on this file https://github.com/TranslatorSRI/Benchmarks/blob/main/MostPrescribed_2019/Data/ConditionToTopDrugs.txt, initially focusing specifically on the `Drug - Protein - BiologicalProcess - Disease` metapath (the second entry on this slide https://docs.google.com/presentation/d/1hF5ceFCBVdImS3-fDaN9SGafjcItWMDU5teSNn3SXs0/edit#slide=id.g113900f19fd_0_335).

**Comment by andrewsu** [comment]
Created the PR above based on new code in [this notebook](https://github.com/SuLab/DMDB_Analysis/blob/main/1_code/5_create_translator_benchmark.ipynb) in https://github.com/SuLab/DMDB_Analysis/commit/d69040668d9ae4b170c2a4296f9166f5accc86c0.

**Comment by maximusunc** [comment]
Closing as this benchmark was added.
