### ISSUE TITLE
Create benchmark for rare diseases based on GTRx and/or FDA's OOPD

### ISSUE THREAD

**Issue by andrewsu** [TranslatorSRI/Benchmarks#20]
Previously in https://github.com/TranslatorSRI/Benchmarks/pull/19, I created a benchmark associated with DrugCentral, which mostly focuses on common diseases and treatments.  This issue is to propose and track progress/discussion toward the creation of a benchmark focused on rare diseases and treatments.  

Possible data sources for rare diseases and treatments include:
* GTRX
   * website: https://gtrx.rbsapp.net/
   * api: https://biothings.ncats.io/gtrx
* OOPD
   * website: https://www.accessdata.fda.gov/scripts/opdlisting/oopd/
   * api: https://mychem.info/v1/query?q=_exists_:fda_orphan_drug&fields=fda_orphan_drug
        * note, the API has older data, but the diseases have been normalized to UMLS

**Comment by andrewsu** [comment]
also remembering that we have a related issue #6 , which has an open PR #10

**Comment by ngk5** [comment]
I created 3 benchmarks - GTRx, OOPD, and RareDisease (combination of GTRx and OOPD) - which can be found here: https://github.com/ngk5/Benchmarks/tree/main/config

Each benchmark contains 
- Jupyter Notebook that retrieves indications from the associated API
- `data_full.tsv` with all indications before further processing, includes some attributes that may be helpful for filtering
- `data.tsv` (subset of `data_full.tsv`) used to run the benchmark (GTRx and OOPD each have 20 entries, RareDisease has 50)
- templates folder with `treats.json` (essentially the same in all 3 benchmarks)

Upon testing, each of these are returning a MRR of ~0.3 which seems as expected according to [this analysis](https://github.com/NCATSTranslator/Feedback/issues/100#issuecomment-1610158327). Also note that some filtering decisions on the data.tsv files (e.g. only keeping cases with one drug per disease) were done to simplify data processing and to follow [get_indications.py](https://github.com/TranslatorSRI/Benchmarks/blob/main/config/DrugCentral_creative/get_indications.py), but should be easily changeable from the respective benchmark's `data_full.tsv`.

Please take a look and let me know of any improvements!

**Comment by andrewsu** [comment]
Given the merge of #23, going to close this issue as successfully completed
